return {
	'icons',
	'theming',
	'tabs',
	'explorer',
	'modeline',
	'telescope',

	'lsp',
	'neogit',
	'treesitter',
	'completion',
	'grammar',

	'web',
	'languages.nix',
	'languages.lua',
	'languages.rust',
	'languages.json',
	'languages.java',
	'languages.python',
	'languages.dhall',
	'languages.latex',
	'languages.astro',
	'languages.asm',
	'languages.go',
	'languages.c',
	'languages.fish',
	'languages.bash',
	'languages.sql',
	'languages.haskell',
	'languages.matlab',
	'languages.gdscript',
	'languages.antlr',
	'languages.jsonnet',
	'languages.elixir',
	'languages.verilog',
}
